use std::path::Path;
use crate::models::{DetectedProject, DetectedService};

pub struct FrameworkDetector;

impl FrameworkDetector {
    /// Inspect directory and return auto-detected framework metadata & generated YAML
    pub fn detect(dir_path: &str) -> DetectedProject {
        let root = Path::new(dir_path);
        if !root.exists() {
            return Self::fallback_default("Invalid Path", 3000);
        }

        // Check for existing mybox.yml / docker-compose.yml first
        if root.join("mybox.yml").exists() || root.join("mybox.yaml").exists() {
            let content = std::fs::read_to_string(root.join("mybox.yml"))
                .or_else(|_| std::fs::read_to_string(root.join("mybox.yaml")))
                .unwrap_or_default();
            return DetectedProject {
                framework_id: "custom_mybox".into(),
                name: "Existing myBox Project".into(),
                category: "Custom Configuration".into(),
                description: "Existing mybox.yml configuration detected in project root".into(),
                default_port: 3000,
                icon: "custom".into(),
                runtime_image: "custom".into(),
                start_command: "mybox up".into(),
                detected_files: vec!["mybox.yml".into()],
                is_multi_service: false,
                generated_yaml: content,
                services: vec![],
            };
        }

        if root.join("docker-compose.yml").exists() || root.join("docker-compose.yaml").exists() {
            let file = if root.join("docker-compose.yml").exists() { "docker-compose.yml" } else { "docker-compose.yaml" };
            let content = std::fs::read_to_string(root.join(file)).unwrap_or_default();
            return DetectedProject {
                framework_id: "custom_compose".into(),
                name: "Docker Compose Project".into(),
                category: "Compose Configuration".into(),
                description: format!("Existing {} configuration found", file),
                default_port: 3000,
                icon: "custom".into(),
                runtime_image: "custom".into(),
                start_command: "mybox up".into(),
                detected_files: vec![file.into()],
                is_multi_service: true,
                generated_yaml: content,
                services: vec![],
            };
        }

        // 1. Check Multi-service Project (e.g. frontend/ + backend/ or client/ + server/)
        let has_frontend_dir = root.join("frontend").is_dir() || root.join("client").is_dir() || root.join("web").is_dir();
        let has_backend_dir = root.join("backend").is_dir() || root.join("server").is_dir() || root.join("api").is_dir();

        if has_frontend_dir && has_backend_dir {
            let f_name = if root.join("frontend").is_dir() { "frontend" } else if root.join("client").is_dir() { "client" } else { "web" };
            let b_name = if root.join("backend").is_dir() { "backend" } else if root.join("server").is_dir() { "server" } else { "api" };

            let yaml = format!(
r#"# Auto-generated by myBox (https://ucdreams.com)
version: '3.8'

services:
  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./{f_name}:/app
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    command: sh -c "npm install && npm run dev || npm start"
    depends_on:
      - backend

  backend:
    image: python:3.12-slim
    working_dir: /app
    volumes:
      - ./{b_name}:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://mybox:mybox123@database:5432/mybox_db
      - REDIS_URL=redis://cache:6379/0
    command: sh -c "pip install -r requirements.txt 2>/dev/null || true && python main.py"
    depends_on:
      - database

  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: mybox
      POSTGRES_PASSWORD: mybox123
      POSTGRES_DB: mybox_db
    ports:
      - "5432:5432"
    volumes:
      - mybox_pgdata:/var/lib/postgresql/data

  cache:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"

volumes:
  mybox_pgdata:
"#, f_name=f_name, b_name=b_name);

            return DetectedProject {
                framework_id: "fullstack_multi".into(),
                name: "Fullstack App (Frontend + Backend + DB)".into(),
                category: "Fullstack Architecture".into(),
                description: format!("Detected dual-service stack: {}/ (Node.js) & {}/ (API) with PostgreSQL & Redis", f_name, b_name),
                default_port: 3000,
                icon: "database".into(),
                runtime_image: "node:20-alpine & python:3.12-slim".into(),
                start_command: "mybox up".into(),
                detected_files: vec![format!("{}/", f_name), format!("{}/", b_name)],
                is_multi_service: true,
                generated_yaml: yaml,
                services: vec![
                    DetectedService { name: "frontend".into(), role: "Frontend UI (Port 3000)".into(), image: "node:20-alpine".into(), port: 3000, env_vars: vec!["NEXT_PUBLIC_API_URL".into()] },
                    DetectedService { name: "backend".into(), role: "Backend API (Port 8000)".into(), image: "python:3.12-slim".into(), port: 8000, env_vars: vec!["DATABASE_URL".into()] },
                    DetectedService { name: "database".into(), role: "PostgreSQL 16 DB".into(), image: "postgres:16-alpine".into(), port: 5432, env_vars: vec!["POSTGRES_DB".into()] },
                    DetectedService { name: "cache".into(), role: "Redis Cache".into(), image: "redis:7.2-alpine".into(), port: 6379, env_vars: vec![] },
                ],
            };
        }

        // 2. JavaScript / TypeScript Ecosystem (package.json check)
        if root.join("package.json").exists() {
            let pkg_content = std::fs::read_to_string(root.join("package.json")).unwrap_or_default().to_lowercase();
            let mut detected_files = vec!["package.json".to_string()];

            // Next.js
            if pkg_content.contains("\"next\"") || root.join("next.config.js").exists() || root.join("next.config.ts").exists() || root.join("next.config.mjs").exists() {
                if root.join("next.config.js").exists() { detected_files.push("next.config.js".into()); }
                return DetectedProject {
                    framework_id: "nextjs".into(),
                    name: "Next.js (React Fullstack)".into(),
                    category: "JavaScript / TypeScript".into(),
                    description: "Detected Next.js framework with Server-Side Rendering & App Router".into(),
                    default_port: 3000,
                    icon: "nextjs".into(),
                    runtime_image: "node:20-alpine".into(),
                    start_command: "npm run dev".into(),
                    detected_files,
                    is_multi_service: false,
                    generated_yaml: Self::generate_node_yaml(3000, "npm run dev"),
                    services: vec![DetectedService { name: "web".into(), role: "Next.js App".into(), image: "node:20-alpine".into(), port: 3000, env_vars: vec!["NODE_ENV=development".into()] }],
                };
            }

            // Nuxt (Vue)
            if pkg_content.contains("\"nuxt\"") || root.join("nuxt.config.ts").exists() || root.join("nuxt.config.js").exists() {
                return DetectedProject {
                    framework_id: "nuxt".into(),
                    name: "Nuxt.js (Vue Fullstack)".into(),
                    category: "JavaScript / TypeScript".into(),
                    description: "Detected Nuxt.js Vue fullstack framework with fast SSR".into(),
                    default_port: 3000,
                    icon: "vue".into(),
                    runtime_image: "node:20-alpine".into(),
                    start_command: "npm run dev".into(),
                    detected_files,
                    is_multi_service: false,
                    generated_yaml: Self::generate_node_yaml(3000, "npm run dev"),
                    services: vec![DetectedService { name: "web".into(), role: "Nuxt.js App".into(), image: "node:20-alpine".into(), port: 3000, env_vars: vec![] }],
                };
            }

            // Svelte / SvelteKit
            if pkg_content.contains("\"@sveltejs/kit\"") || pkg_content.contains("\"svelte\"") || root.join("svelte.config.js").exists() {
                return DetectedProject {
                    framework_id: "sveltekit".into(),
                    name: "Svelte / SvelteKit".into(),
                    category: "JavaScript / TypeScript".into(),
                    description: "Detected SvelteKit modern reactive web application".into(),
                    default_port: 5173,
                    icon: "svelte".into(),
                    runtime_image: "node:20-alpine".into(),
                    start_command: "npm run dev -- --host 0.0.0.0".into(),
                    detected_files,
                    is_multi_service: false,
                    generated_yaml: Self::generate_node_yaml(5173, "npm run dev -- --host 0.0.0.0"),
                    services: vec![DetectedService { name: "web".into(), role: "SvelteKit App".into(), image: "node:20-alpine".into(), port: 5173, env_vars: vec![] }],
                };
            }

            // Astro
            if pkg_content.contains("\"astro\"") || root.join("astro.config.mjs").exists() {
                return DetectedProject {
                    framework_id: "astro".into(),
                    name: "Astro Web Framework".into(),
                    category: "JavaScript / TypeScript".into(),
                    description: "Detected Astro ultra-fast content-focused web framework".into(),
                    default_port: 4321,
                    icon: "astro".into(),
                    runtime_image: "node:20-alpine".into(),
                    start_command: "npm run dev -- --host".into(),
                    detected_files,
                    is_multi_service: false,
                    generated_yaml: Self::generate_node_yaml(4321, "npm run dev -- --host"),
                    services: vec![DetectedService { name: "web".into(), role: "Astro App".into(), image: "node:20-alpine".into(), port: 4321, env_vars: vec![] }],
                };
            }

            // Remix
            if pkg_content.contains("\"@remix-run") {
                return DetectedProject {
                    framework_id: "remix".into(),
                    name: "Remix (React)".into(),
                    category: "JavaScript / TypeScript".into(),
                    description: "Detected Remix full-stack React framework".into(),
                    default_port: 3000,
                    icon: "react".into(),
                    runtime_image: "node:20-alpine".into(),
                    start_command: "npm run dev".into(),
                    detected_files,
                    is_multi_service: false,
                    generated_yaml: Self::generate_node_yaml(3000, "npm run dev"),
                    services: vec![DetectedService { name: "web".into(), role: "Remix App".into(), image: "node:20-alpine".into(), port: 3000, env_vars: vec![] }],
                };
            }

            // Vite + React / Vue / Vanilla
            if pkg_content.contains("\"vite\"") || root.join("vite.config.ts").exists() || root.join("vite.config.js").exists() {
                let name = if pkg_content.contains("\"react\"") { "React (Vite)" } else if pkg_content.contains("\"vue\"") { "Vue 3 (Vite)" } else { "Vite Frontend" };
                return DetectedProject {
                    framework_id: "vite".into(),
                    name: name.into(),
                    category: "JavaScript / TypeScript".into(),
                    description: "Detected Vite high-speed modern frontend development server".into(),
                    default_port: 5173,
                    icon: "react".into(),
                    runtime_image: "node:20-alpine".into(),
                    start_command: "npm run dev -- --host".into(),
                    detected_files,
                    is_multi_service: false,
                    generated_yaml: Self::generate_node_yaml(5173, "npm run dev -- --host"),
                    services: vec![DetectedService { name: "web".into(), role: "Frontend Dev Server".into(), image: "node:20-alpine".into(), port: 5173, env_vars: vec![] }],
                };
            }

            // NestJS
            if pkg_content.contains("\"@nestjs") {
                return DetectedProject {
                    framework_id: "nestjs".into(),
                    name: "NestJS Backend API".into(),
                    category: "JavaScript / TypeScript".into(),
                    description: "Detected NestJS enterprise TypeScript backend framework".into(),
                    default_port: 3000,
                    icon: "node".into(),
                    runtime_image: "node:20-alpine".into(),
                    start_command: "npm run start:dev".into(),
                    detected_files,
                    is_multi_service: false,
                    generated_yaml: Self::generate_node_yaml(3000, "npm run start:dev"),
                    services: vec![DetectedService { name: "api".into(), role: "NestJS Server".into(), image: "node:20-alpine".into(), port: 3000, env_vars: vec![] }],
                };
            }

            // General Node.js / Express
            return DetectedProject {
                framework_id: "node".into(),
                name: "Node.js / Express Server".into(),
                category: "JavaScript / TypeScript".into(),
                description: "Detected Node.js application with npm package manifest".into(),
                default_port: 3000,
                icon: "node".into(),
                runtime_image: "node:20-alpine".into(),
                start_command: "npm start".into(),
                detected_files,
                is_multi_service: false,
                generated_yaml: Self::generate_node_yaml(3000, "npm start"),
                services: vec![DetectedService { name: "web".into(), role: "Node Server".into(), image: "node:20-alpine".into(), port: 3000, env_vars: vec![] }],
            };
        }

        // 3. Python Ecosystem (manage.py, requirements.txt, pyproject.toml)
        if root.join("manage.py").exists() {
            return DetectedProject {
                framework_id: "django".into(),
                name: "Django Web Framework".into(),
                category: "Python".into(),
                description: "Detected Django full-stack Python web framework (manage.py found)".into(),
                default_port: 8000,
                icon: "python".into(),
                runtime_image: "python:3.12-slim".into(),
                start_command: "python manage.py runserver 0.0.0.0:8000".into(),
                detected_files: vec!["manage.py".into()],
                is_multi_service: false,
                generated_yaml: format!(
r#"# Generated by myBox (https://ucdreams.com)
version: '3.8'

services:
  web:
    image: python:3.12-slim
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: sh -c "pip install -r requirements.txt 2>/dev/null || true && python manage.py migrate 2>/dev/null || true && python manage.py runserver 0.0.0.0:8000"
"#),
                services: vec![DetectedService { name: "web".into(), role: "Django App Server".into(), image: "python:3.12-slim".into(), port: 8000, env_vars: vec!["PYTHONUNBUFFERED=1".into()] }],
            };
        }

        if root.join("requirements.txt").exists() || root.join("pyproject.toml").exists() || root.join("Pipfile").exists() || root.join("main.py").exists() || root.join("app.py").exists() {
            let req_content = std::fs::read_to_string(root.join("requirements.txt"))
                .or_else(|_| std::fs::read_to_string(root.join("pyproject.toml")))
                .unwrap_or_default().to_lowercase();

            let (name, cmd, port, desc) = if req_content.contains("fastapi") {
                ("FastAPI High-Speed API", "uvicorn main:app --host 0.0.0.0 --port 8000 --reload", 8000, "Detected FastAPI modern asynchronous Python API framework")
            } else if req_content.contains("flask") {
                ("Flask Microframework", "flask run --host=0.0.0.0 --port=5000", 5000, "Detected Flask Python lightweight web server")
            } else if req_content.contains("streamlit") {
                ("Streamlit AI/Data App", "streamlit run app.py --server.port=8501 --server.address=0.0.0.0", 8501, "Detected Streamlit interactive data and AI application")
            } else {
                ("Python Application", "python main.py", 8000, "Detected Python application with dependencies")
            };

            return DetectedProject {
                framework_id: "python".into(),
                name: name.into(),
                category: "Python".into(),
                description: desc.into(),
                default_port: port,
                icon: "python".into(),
                runtime_image: "python:3.12-slim".into(),
                start_command: cmd.into(),
                detected_files: vec!["requirements.txt".into()],
                is_multi_service: false,
                generated_yaml: format!(
r#"# Generated by myBox (https://ucdreams.com)
version: '3.8'

services:
  api:
    image: python:3.12-slim
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "{port}:{port}"
    environment:
      - PYTHONUNBUFFERED=1
    command: sh -c "pip install -r requirements.txt 2>/dev/null || true && {cmd}"
"#, port=port, cmd=cmd),
                services: vec![DetectedService { name: "api".into(), role: "Python Service".into(), image: "python:3.12-slim".into(), port, env_vars: vec!["PYTHONUNBUFFERED=1".into()] }],
            };
        }

        // 4. PHP Ecosystem (composer.json, artisan, wp-config.php)
        if root.join("artisan").exists() || (root.join("composer.json").exists() && std::fs::read_to_string(root.join("composer.json")).unwrap_or_default().contains("laravel/framework")) {
            return DetectedProject {
                framework_id: "laravel".into(),
                name: "Laravel (PHP 8.3)".into(),
                category: "PHP".into(),
                description: "Detected Laravel modern PHP web application (artisan CLI found)".into(),
                default_port: 8000,
                icon: "php".into(),
                runtime_image: "php:8.3-cli-alpine".into(),
                start_command: "php artisan serve --host=0.0.0.0 --port=8000".into(),
                detected_files: vec!["artisan".into()],
                is_multi_service: false,
                generated_yaml: format!(
r#"# Generated by myBox (https://ucdreams.com)
version: '3.8'

services:
  web:
    image: php:8.3-cli-alpine
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    command: sh -c "composer install 2>/dev/null || true && php artisan serve --host=0.0.0.0 --port=8000"
"#),
                services: vec![DetectedService { name: "web".into(), role: "Laravel Web Server".into(), image: "php:8.3-cli-alpine".into(), port: 8000, env_vars: vec![] }],
            };
        }

        if root.join("wp-config.php").exists() || root.join("wp-content").is_dir() {
            return DetectedProject {
                framework_id: "wordpress".into(),
                name: "WordPress CMS + MySQL".into(),
                category: "PHP".into(),
                description: "Detected WordPress installation with Apache & MySQL requirement".into(),
                default_port: 8080,
                icon: "php".into(),
                runtime_image: "wordpress:php8.3-apache".into(),
                start_command: "apache2-foreground".into(),
                detected_files: vec!["wp-config.php".into()],
                is_multi_service: true,
                generated_yaml: format!(
r#"# Generated by myBox (https://ucdreams.com)
version: '3.8'

services:
  wordpress:
    image: wordpress:php8.3-apache
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_pass
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_pass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - mybox_wp_db:/var/lib/mysql

volumes:
  mybox_wp_db:
"#),
                services: vec![
                    DetectedService { name: "wordpress".into(), role: "WordPress + Apache".into(), image: "wordpress:php8.3-apache".into(), port: 8080, env_vars: vec!["WORDPRESS_DB_HOST".into()] },
                    DetectedService { name: "db".into(), role: "MySQL 8.0 Database".into(), image: "mysql:8.0".into(), port: 3306, env_vars: vec!["MYSQL_DATABASE".into()] },
                ],
            };
        }

        // 5. Rust (Cargo.toml)
        if root.join("Cargo.toml").exists() {
            return DetectedProject {
                framework_id: "rust".into(),
                name: "Rust Web / System Application".into(),
                category: "Rust".into(),
                description: "Detected Rust project (Cargo workspace or binary crate)".into(),
                default_port: 8080,
                icon: "rust".into(),
                runtime_image: "rust:1.77-alpine".into(),
                start_command: "cargo run".into(),
                detected_files: vec!["Cargo.toml".into()],
                is_multi_service: false,
                generated_yaml: format!(
r#"# Generated by myBox (https://ucdreams.com)
version: '3.8'

services:
  app:
    image: rust:1.77-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: sh -c "cargo run"
"#),
                services: vec![DetectedService { name: "app".into(), role: "Rust Binary Server".into(), image: "rust:1.77-alpine".into(), port: 8080, env_vars: vec![] }],
            };
        }

        // 6. Go (go.mod)
        if root.join("go.mod").exists() || root.join("main.go").exists() {
            return DetectedProject {
                framework_id: "go".into(),
                name: "Go (Golang) Microservice".into(),
                category: "Go".into(),
                description: "Detected Go project with go.mod module manifest".into(),
                default_port: 8080,
                icon: "go".into(),
                runtime_image: "golang:1.22-alpine".into(),
                start_command: "go run .".into(),
                detected_files: vec!["go.mod".into()],
                is_multi_service: false,
                generated_yaml: format!(
r#"# Generated by myBox (https://ucdreams.com)
version: '3.8'

services:
  api:
    image: golang:1.22-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: sh -c "go run ."
"#),
                services: vec![DetectedService { name: "api".into(), role: "Go API Service".into(), image: "golang:1.22-alpine".into(), port: 8080, env_vars: vec![] }],
            };
        }

        // 7. Ruby (Gemfile)
        if root.join("Gemfile").exists() {
            let gem_content = std::fs::read_to_string(root.join("Gemfile")).unwrap_or_default().to_lowercase();
            let is_rails = gem_content.contains("rails") || root.join("config/application.rb").exists();
            let name = if is_rails { "Ruby on Rails App" } else { "Ruby Application" };
            let cmd = if is_rails { "bundle exec rails server -b 0.0.0.0 -p 3000" } else { "ruby app.py" };
            let port = if is_rails { 3000 } else { 4567 };

            return DetectedProject {
                framework_id: "ruby".into(),
                name: name.into(),
                category: "Ruby".into(),
                description: "Detected Ruby application with Bundler Gemfile".into(),
                default_port: port,
                icon: "ruby".into(),
                runtime_image: "ruby:3.3-alpine".into(),
                start_command: cmd.into(),
                detected_files: vec!["Gemfile".into()],
                is_multi_service: false,
                generated_yaml: format!(
r#"# Generated by myBox (https://ucdreams.com)
version: '3.8'

services:
  web:
    image: ruby:3.3-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "{port}:{port}"
    command: sh -c "bundle install 2>/dev/null || true && {cmd}"
"#, port=port, cmd=cmd),
                services: vec![DetectedService { name: "web".into(), role: "Ruby App".into(), image: "ruby:3.3-alpine".into(), port, env_vars: vec![] }],
            };
        }

        // 8. Java / JVM / Spring Boot (pom.xml, build.gradle)
        if root.join("pom.xml").exists() || root.join("build.gradle").exists() || root.join("build.gradle.kts").exists() {
            return DetectedProject {
                framework_id: "springboot".into(),
                name: "Java / Spring Boot".into(),
                category: "Java / JVM".into(),
                description: "Detected Java Maven / Gradle Spring Boot backend application".into(),
                default_port: 8080,
                icon: "java".into(),
                runtime_image: "eclipse-temurin:21-alpine".into(),
                start_command: "./mvnw spring-boot:run || ./gradlew bootRun".into(),
                detected_files: vec!["pom.xml".into()],
                is_multi_service: false,
                generated_yaml: format!(
r#"# Generated by myBox (https://ucdreams.com)
version: '3.8'

services:
  app:
    image: eclipse-temurin:21-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: sh -c "./mvnw spring-boot:run 2>/dev/null || ./gradlew bootRun 2>/dev/null || java -jar target/*.jar"
"#),
                services: vec![DetectedService { name: "app".into(), role: "Spring Boot Server".into(), image: "eclipse-temurin:21-alpine".into(), port: 8080, env_vars: vec![] }],
            };
        }

        // 9. .NET / C# / ASP.NET
        let has_csproj = std::fs::read_dir(root)
            .map(|entries| entries.filter_map(|e| e.ok()).any(|e| e.file_name().to_string_lossy().ends_with(".csproj") || e.file_name().to_string_lossy().ends_with(".sln")))
            .unwrap_or(false);

        if has_csproj || root.join("Program.cs").exists() {
            return DetectedProject {
                framework_id: "dotnet".into(),
                name: ".NET / ASP.NET Core API".into(),
                category: ".NET".into(),
                description: "Detected .NET / C# application project".into(),
                default_port: 5000,
                icon: "dotnet".into(),
                runtime_image: "mcr.microsoft.com/dotnet/sdk:8.0-alpine".into(),
                start_command: "dotnet run --urls=http://0.0.0.0:5000".into(),
                detected_files: vec!["*.csproj".into()],
                is_multi_service: false,
                generated_yaml: format!(
r#"# Generated by myBox (https://ucdreams.com)
version: '3.8'

services:
  api:
    image: mcr.microsoft.com/dotnet/sdk:8.0-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
    command: sh -c "dotnet run --urls=http://0.0.0.0:5000"
"#),
                services: vec![DetectedService { name: "api".into(), role: ".NET Core App".into(), image: "mcr.microsoft.com/dotnet/sdk:8.0-alpine".into(), port: 5000, env_vars: vec!["ASPNETCORE_URLS=http://+:5000".into()] }],
            };
        }

        // 10. Flutter / Dart (pubspec.yaml)
        if root.join("pubspec.yaml").exists() {
            return DetectedProject {
                framework_id: "flutter".into(),
                name: "Flutter Web / Dart App".into(),
                category: "Mobile & Web".into(),
                description: "Detected Flutter / Dart project (pubspec.yaml found)".into(),
                default_port: 8080,
                icon: "flutter".into(),
                runtime_image: "ghcr.io/cirruslabs/flutter:latest".into(),
                start_command: "flutter run -d web-server --web-port 8080 --web-hostname 0.0.0.0".into(),
                detected_files: vec!["pubspec.yaml".into()],
                is_multi_service: false,
                generated_yaml: format!(
r#"# Generated by myBox (https://ucdreams.com)
version: '3.8'

services:
  web:
    image: ghcr.io/cirruslabs/flutter:latest
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: sh -c "flutter pub get && flutter run -d web-server --web-port 8080 --web-hostname 0.0.0.0"
"#),
                services: vec![DetectedService { name: "web".into(), role: "Flutter Web Server".into(), image: "ghcr.io/cirruslabs/flutter:latest".into(), port: 8080, env_vars: vec![] }],
            };
        }

        // Fallback default
        Self::fallback_default("General Fullstack + PostgreSQL", 3000)
    }

    fn generate_node_yaml(port: u16, command: &str) -> String {
        format!(
r#"# Auto-generated by myBox (https://ucdreams.com)
version: '3.8'

services:
  web:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "{port}:{port}"
    environment:
      - NODE_ENV=development
      - PORT={port}
    command: sh -c "npm install 2>/dev/null || true && {command}"
"#, port=port, command=command)
    }

    fn fallback_default(name: &str, port: u16) -> DetectedProject {
        let yaml = format!(
r#"# Generated by myBox (https://ucdreams.com)
version: '3.8'

services:
  app:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "{port}:{port}"
    environment:
      - DATABASE_URL=postgres://mybox:mybox123@db:5432/mybox_db
    command: sh -c "npm install 2>/dev/null || true && npm start"
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: mybox
      POSTGRES_PASSWORD: mybox123
      POSTGRES_DB: mybox_db
    ports:
      - "5432:5432"
    volumes:
      - mybox_pgdata:/var/lib/postgresql/data

volumes:
  mybox_pgdata:
"#, port=port);

        DetectedProject {
            framework_id: "generic_fullstack".into(),
            name: name.into(),
            category: "General Application".into(),
            description: "Ready-to-run container sandbox with persistent PostgreSQL database".into(),
            default_port: port,
            icon: "database".into(),
            runtime_image: "node:20-alpine & postgres:16-alpine".into(),
            start_command: "mybox up".into(),
            detected_files: vec![],
            is_multi_service: true,
            generated_yaml: yaml,
            services: vec![
                DetectedService { name: "app".into(), role: "Application Server".into(), image: "node:20-alpine".into(), port, env_vars: vec!["DATABASE_URL".into()] },
                DetectedService { name: "db".into(), role: "PostgreSQL Database".into(), image: "postgres:16-alpine".into(), port: 5432, env_vars: vec!["POSTGRES_DB".into()] },
            ],
        }
    }
}
