use std::path::Path;
use crate::models::{DetectedProject, DetectedService};

pub struct FrameworkDetector;

impl FrameworkDetector {
    /// Probe host OS for the next available non-conflicting port
    pub fn find_available_port(preferred: u16) -> u16 {
        let mut port = preferred;
        for _ in 0..50 {
            if std::net::TcpListener::bind(("127.0.0.1", port)).is_ok() {
                return port;
            }
            port += 1;
        }
        preferred
    }

    /// Inspect directory and return auto-detected framework metadata & generated YAML
    pub fn detect(dir_path: &str) -> DetectedProject {
        let root = Path::new(dir_path);
        if !root.exists() {
            return Self::fallback_default("Invalid Path", 3000);
        }

        // Check for existing mybox.yaml / mybox.yml / compose configuration first
        if root.join("mybox.yaml").exists() || root.join("mybox.yml").exists() {
            let (file_name, content) = if root.join("mybox.yaml").exists() {
                ("mybox.yaml", std::fs::read_to_string(root.join("mybox.yaml")).unwrap_or_default())
            } else {
                ("mybox.yml", std::fs::read_to_string(root.join("mybox.yml")).unwrap_or_default())
            };
            let folder_name = root
                .file_name()
                .and_then(|n| n.to_str())
                .unwrap_or("myBox Project")
                .to_string();
            return DetectedProject {
                framework_id: "custom_mybox".into(),
                name: folder_name,
                category: "Custom Configuration".into(),
                description: format!("Existing {} configuration detected in project root", file_name),
                default_port: 3000,
                icon: "custom".into(),
                runtime_image: "custom".into(),
                start_command: "mybox up".into(),
                detected_files: vec![file_name.into()],
                is_multi_service: false,
                generated_yaml: content,
                services: vec![],
            };
        }

        if root.join("docker-compose.yml").exists() || root.join("docker-compose.yaml").exists() {
            let file = if root.join("docker-compose.yml").exists() { "docker-compose.yml" } else { "docker-compose.yaml" };
            let content = std::fs::read_to_string(root.join(file)).unwrap_or_default();
            return DetectedProject {
                framework_id: "custom_compose".into(),
                name: "myBox Compose Project".into(),
                category: "Compose Configuration".into(),
                description: format!("Existing {} configuration found", file),
                default_port: 3000,
                icon: "custom".into(),
                runtime_image: "custom".into(),
                start_command: "mybox up".into(),
                detected_files: vec![file.into()],
                is_multi_service: true,
                generated_yaml: content,
                services: vec![],
            };
        }

        // 1. Check Multi-service Project (e.g. frontend/ + backend/ or client/ + server/)
        let has_frontend_dir = root.join("frontend").is_dir() || root.join("client").is_dir() || root.join("web").is_dir();
        let has_backend_dir = root.join("backend").is_dir() || root.join("server").is_dir() || root.join("api").is_dir();

        if has_frontend_dir && has_backend_dir {
            let f_name = if root.join("frontend").is_dir() { "frontend" } else if root.join("client").is_dir() { "client" } else { "web" };
            let b_name = if root.join("backend").is_dir() { "backend" } else if root.join("server").is_dir() { "server" } else { "api" };

            let b_path = root.join(b_name);
            let (b_image, b_cmd, b_role) = if b_path.join("Cargo.toml").exists() {
                ("rust:alpine", "sh -c \"cargo run\"", "Rust API Server (Port 8080)")
            } else if b_path.join("go.mod").exists() {
                ("golang:1.22-alpine", "sh -c \"go run . || go run main.go\"", "Go API Server (Port 8080)")
            } else if b_path.join("package.json").exists() {
                ("node:20-alpine", "sh -c \"npm install && npm start || npm run dev\"", "Node.js API Server (Port 8000)")
            } else {
                ("python:3.12-slim", "sh -c \"pip install -r requirements.txt 2>/dev/null || true && python main.py || python app.py\"", "Python API Server (Port 8000)")
            };

            let f_port = Self::find_available_port(3000);
            let b_base_port = if b_image.starts_with("rust") || b_image.starts_with("golang") { 8080 } else { 8000 };
            let b_port = Self::find_available_port(b_base_port);

            let yaml = format!(
r#"# Auto-generated by myBox (https://ucdreams.com)
services:
  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./{f_name}:/app
    ports:
      - "{f_port}:3000"
    environment:
      - VITE_API_URL=http://localhost:{b_port}
      - NEXT_PUBLIC_API_URL=http://localhost:{b_port}
    command: sh -c "npm install && npm run dev || npm start"
    depends_on:
      - backend

  backend:
    image: {b_image}
    working_dir: /app
    volumes:
      - ./{b_name}:/app
    ports:
      - "{b_port}:{b_base_port}"
    environment:
      - DATABASE_URL=postgres://mybox:mybox123@database:5432/mybox_db
      - REDIS_URL=redis://cache:6379/0
    command: {b_cmd}
    depends_on:
      - database

  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: mybox
      POSTGRES_PASSWORD: mybox123
      POSTGRES_DB: mybox_db
    ports:
      - "5432:5432"
    volumes:
      - mybox_pgdata:/var/lib/postgresql/data

  cache:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"

volumes:
  mybox_pgdata:
"#, f_name=f_name, b_name=b_name, b_image=b_image, b_cmd=b_cmd, b_port=b_port, b_base_port=b_base_port);

            return DetectedProject {
                framework_id: "fullstack_multi".into(),
                name: "Fullstack App (Frontend + Backend + DB)".into(),
                category: "Fullstack Architecture".into(),
                description: format!("Detected dual-service stack: {}/ (Node.js) & {}/ (API) with PostgreSQL & Redis", f_name, b_name),
                default_port: f_port,
                icon: "database".into(),
                runtime_image: format!("node:20-alpine & {}", b_image),
                start_command: "mybox up".into(),
                detected_files: vec![format!("{}/", f_name), format!("{}/", b_name)],
                is_multi_service: true,
                generated_yaml: yaml,
                services: vec![
                    DetectedService { name: "frontend".into(), role: "Frontend UI (Port 3000)".into(), image: "node:20-alpine".into(), port: 3000, env_vars: vec!["NEXT_PUBLIC_API_URL".into()] },
                    DetectedService { name: "backend".into(), role: b_role.into(), image: b_image.into(), port: b_port, env_vars: vec!["DATABASE_URL".into()] },
                    DetectedService { name: "database".into(), role: "PostgreSQL 16 DB".into(), image: "postgres:16-alpine".into(), port: 5432, env_vars: vec!["POSTGRES_DB".into()] },
                    DetectedService { name: "cache".into(), role: "Redis Cache".into(), image: "redis:7.2-alpine".into(), port: 6379, env_vars: vec![] },
                ],
            };
        }

        // 2. JavaScript / TypeScript Ecosystem (package.json check)
        if root.join("package.json").exists() {
            let pkg_content = std::fs::read_to_string(root.join("package.json")).unwrap_or_default().to_lowercase();
            let mut detected_files = vec!["package.json".to_string()];

            // Next.js
            if pkg_content.contains("\"next\"") || root.join("next.config.js").exists() || root.join("next.config.ts").exists() || root.join("next.config.mjs").exists() {
                if root.join("next.config.js").exists() { detected_files.push("next.config.js".into()); }
                let (port, yaml) = Self::generate_node_yaml(3000, "npm run dev");
                return DetectedProject {
                    framework_id: "nextjs".into(),
                    name: "Next.js (React Fullstack)".into(),
                    category: "JavaScript / TypeScript".into(),
                    description: "Detected Next.js framework with Server-Side Rendering & App Router".into(),
                    default_port: port,
                    icon: "nextjs".into(),
                    runtime_image: "node:20-alpine".into(),
                    start_command: "npm run dev".into(),
                    detected_files,
                    is_multi_service: false,
                    generated_yaml: yaml,
                    services: vec![DetectedService { name: "web".into(), role: "Next.js App".into(), image: "node:20-alpine".into(), port, env_vars: vec!["NODE_ENV=development".into()] }],
                };
            }

            // Nuxt (Vue)
            if pkg_content.contains("\"nuxt\"") || root.join("nuxt.config.ts").exists() || root.join("nuxt.config.js").exists() {
                let (port, yaml) = Self::generate_node_yaml(3000, "npm run dev");
                return DetectedProject {
                    framework_id: "nuxt".into(),
                    name: "Nuxt.js (Vue Fullstack)".into(),
                    category: "JavaScript / TypeScript".into(),
                    description: "Detected Nuxt.js Vue fullstack framework with fast SSR".into(),
                    default_port: port,
                    icon: "vue".into(),
                    runtime_image: "node:20-alpine".into(),
                    start_command: "npm run dev".into(),
                    detected_files,
                    is_multi_service: false,
                    generated_yaml: yaml,
                    services: vec![DetectedService { name: "web".into(), role: "Nuxt.js App".into(), image: "node:20-alpine".into(), port, env_vars: vec![] }],
                };
            }

            // Svelte / SvelteKit
            if pkg_content.contains("\"@sveltejs/kit\"") || pkg_content.contains("\"svelte\"") || root.join("svelte.config.js").exists() {
                let (port, yaml) = Self::generate_node_yaml(5173, "npm run dev -- --host 0.0.0.0");
                return DetectedProject {
                    framework_id: "sveltekit".into(),
                    name: "Svelte / SvelteKit".into(),
                    category: "JavaScript / TypeScript".into(),
                    description: "Detected SvelteKit modern reactive web application".into(),
                    default_port: port,
                    icon: "svelte".into(),
                    runtime_image: "node:20-alpine".into(),
                    start_command: "npm run dev -- --host 0.0.0.0".into(),
                    detected_files,
                    is_multi_service: false,
                    generated_yaml: yaml,
                    services: vec![DetectedService { name: "web".into(), role: "SvelteKit App".into(), image: "node:20-alpine".into(), port, env_vars: vec![] }],
                };
            }

            // Astro
            if pkg_content.contains("\"astro\"") || root.join("astro.config.mjs").exists() {
                let (port, yaml) = Self::generate_node_yaml(4321, "npm run dev -- --host");
                return DetectedProject {
                    framework_id: "astro".into(),
                    name: "Astro Web Framework".into(),
                    category: "JavaScript / TypeScript".into(),
                    description: "Detected Astro ultra-fast content-focused web framework".into(),
                    default_port: port,
                    icon: "astro".into(),
                    runtime_image: "node:20-alpine".into(),
                    start_command: "npm run dev -- --host".into(),
                    detected_files,
                    is_multi_service: false,
                    generated_yaml: yaml,
                    services: vec![DetectedService { name: "web".into(), role: "Astro App".into(), image: "node:20-alpine".into(), port, env_vars: vec![] }],
                };
            }

            // Remix
            if pkg_content.contains("\"@remix-run") {
                let (port, yaml) = Self::generate_node_yaml(3000, "npm run dev");
                return DetectedProject {
                    framework_id: "remix".into(),
                    name: "Remix (React)".into(),
                    category: "JavaScript / TypeScript".into(),
                    description: "Detected Remix full-stack React framework".into(),
                    default_port: port,
                    icon: "react".into(),
                    runtime_image: "node:20-alpine".into(),
                    start_command: "npm run dev".into(),
                    detected_files,
                    is_multi_service: false,
                    generated_yaml: yaml,
                    services: vec![DetectedService { name: "web".into(), role: "Remix App".into(), image: "node:20-alpine".into(), port, env_vars: vec![] }],
                };
            }

            // Vite + React / Vue / Vanilla
            if pkg_content.contains("\"vite\"") || root.join("vite.config.ts").exists() || root.join("vite.config.js").exists() {
                let name = if pkg_content.contains("\"react\"") { "React (Vite)" } else if pkg_content.contains("\"vue\"") { "Vue 3 (Vite)" } else { "Vite Frontend" };
                let (port, yaml) = Self::generate_node_yaml(5173, "npm run dev -- --host");
                return DetectedProject {
                    framework_id: "vite".into(),
                    name: name.into(),
                    category: "JavaScript / TypeScript".into(),
                    description: "Detected Vite high-speed modern frontend development server".into(),
                    default_port: port,
                    icon: "react".into(),
                    runtime_image: "node:20-alpine".into(),
                    start_command: "npm run dev -- --host".into(),
                    detected_files,
                    is_multi_service: false,
                    generated_yaml: yaml,
                    services: vec![DetectedService { name: "web".into(), role: "Frontend Dev Server".into(), image: "node:20-alpine".into(), port, env_vars: vec![] }],
                };
            }

            // NestJS
            if pkg_content.contains("\"@nestjs") {
                let (port, yaml) = Self::generate_node_yaml(3000, "npm run start:dev");
                return DetectedProject {
                    framework_id: "nestjs".into(),
                    name: "NestJS Backend API".into(),
                    category: "JavaScript / TypeScript".into(),
                    description: "Detected NestJS enterprise TypeScript backend framework".into(),
                    default_port: port,
                    icon: "node".into(),
                    runtime_image: "node:20-alpine".into(),
                    start_command: "npm run start:dev".into(),
                    detected_files,
                    is_multi_service: false,
                    generated_yaml: yaml,
                    services: vec![DetectedService { name: "api".into(), role: "NestJS Server".into(), image: "node:20-alpine".into(), port, env_vars: vec![] }],
                };
            }

            // General Node.js / Express
            let (port, yaml) = Self::generate_node_yaml(3000, "npm start");
            return DetectedProject {
                framework_id: "node".into(),
                name: "Node.js / Express Server".into(),
                category: "JavaScript / TypeScript".into(),
                description: "Detected Node.js application with npm package manifest".into(),
                default_port: port,
                icon: "node".into(),
                runtime_image: "node:20-alpine".into(),
                start_command: "npm start".into(),
                detected_files,
                is_multi_service: false,
                generated_yaml: yaml,
                services: vec![DetectedService { name: "web".into(), role: "Node Server".into(), image: "node:20-alpine".into(), port, env_vars: vec![] }],
            };
        }

        // 3. Python Ecosystem (manage.py, requirements.txt, pyproject.toml)
        if root.join("manage.py").exists() {
            let port = Self::find_available_port(8000);
            return DetectedProject {
                framework_id: "django".into(),
                name: "Django Web Framework".into(),
                category: "Python".into(),
                description: "Detected Django full-stack Python web framework (manage.py found)".into(),
                default_port: port,
                icon: "python".into(),
                runtime_image: "python:3.12-slim".into(),
                start_command: "python manage.py runserver 0.0.0.0:8000".into(),
                detected_files: vec!["manage.py".into()],
                is_multi_service: false,
                generated_yaml: format!(
r#"# Generated by myBox (https://ucdreams.com)


services:
  web:
    image: python:3.12-slim
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "{port}:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: sh -c "pip install -r requirements.txt 2>/dev/null || true && python manage.py migrate 2>/dev/null || true && python manage.py runserver 0.0.0.0:8000"
"#, port=port),
                services: vec![DetectedService { name: "web".into(), role: "Django App Server".into(), image: "python:3.12-slim".into(), port, env_vars: vec!["PYTHONUNBUFFERED=1".into()] }],
            };
        }

        if root.join("requirements.txt").exists() || root.join("pyproject.toml").exists() || root.join("Pipfile").exists() || root.join("main.py").exists() || root.join("app.py").exists() {
            let req_content = std::fs::read_to_string(root.join("requirements.txt"))
                .or_else(|_| std::fs::read_to_string(root.join("pyproject.toml")))
                .unwrap_or_default().to_lowercase();

            let (name, cmd, base_port, desc) = if req_content.contains("fastapi") {
                ("FastAPI High-Speed API", "uvicorn main:app --host 0.0.0.0 --port 8000 --reload", 8000, "Detected FastAPI modern asynchronous Python API framework")
            } else if req_content.contains("flask") {
                ("Flask Microframework", "flask run --host=0.0.0.0 --port=5000", 5000, "Detected Flask Python lightweight web server")
            } else if req_content.contains("streamlit") {
                ("Streamlit AI/Data App", "streamlit run app.py --server.port=8501 --server.address=0.0.0.0", 8501, "Detected Streamlit interactive data and AI application")
            } else {
                ("Python Application", "python main.py", 8000, "Detected Python application with dependencies")
            };
            let port = Self::find_available_port(base_port);

            return DetectedProject {
                framework_id: "python".into(),
                name: name.into(),
                category: "Python".into(),
                description: desc.into(),
                default_port: port,
                icon: "python".into(),
                runtime_image: "python:3.12-slim".into(),
                start_command: cmd.into(),
                detected_files: vec!["requirements.txt".into()],
                is_multi_service: false,
                generated_yaml: format!(
r#"# Generated by myBox (https://ucdreams.com)


services:
  api:
    image: python:3.12-slim
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "{port}:{base_port}"
    environment:
      - PYTHONUNBUFFERED=1
    command: sh -c "pip install -r requirements.txt 2>/dev/null || true && {cmd}"
"#, port=port, base_port=base_port, cmd=cmd),
                services: vec![DetectedService { name: "api".into(), role: "Python Service".into(), image: "python:3.12-slim".into(), port, env_vars: vec!["PYTHONUNBUFFERED=1".into()] }],
            };
        }

        // 4. PHP Ecosystem (composer.json, artisan, wp-config.php)
        if root.join("artisan").exists() || (root.join("composer.json").exists() && std::fs::read_to_string(root.join("composer.json")).unwrap_or_default().contains("laravel/framework")) {
            let port = Self::find_available_port(8000);
            return DetectedProject {
                framework_id: "laravel".into(),
                name: "Laravel (PHP 8.3)".into(),
                category: "PHP".into(),
                description: "Detected Laravel modern PHP web application (artisan CLI found)".into(),
                default_port: port,
                icon: "php".into(),
                runtime_image: "php:8.3-cli-alpine".into(),
                start_command: "php artisan serve --host=0.0.0.0 --port=8000".into(),
                detected_files: vec!["artisan".into()],
                is_multi_service: false,
                generated_yaml: format!(
r#"# Generated by myBox (https://ucdreams.com)


services:
  web:
    image: php:8.3-cli-alpine
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "{port}:8000"
    command: sh -c "composer install 2>/dev/null || true && php artisan serve --host=0.0.0.0 --port=8000"
"#, port=port),
                services: vec![DetectedService { name: "web".into(), role: "Laravel Web Server".into(), image: "php:8.3-cli-alpine".into(), port, env_vars: vec![] }],
            };
        }

        if root.join("wp-config.php").exists() || root.join("wp-content").is_dir() {
            let port = Self::find_available_port(8080);
            return DetectedProject {
                framework_id: "wordpress".into(),
                name: "WordPress CMS + MySQL".into(),
                category: "PHP".into(),
                description: "Detected WordPress installation with Apache & MySQL requirement".into(),
                default_port: port,
                icon: "php".into(),
                runtime_image: "wordpress:php8.3-apache".into(),
                start_command: "apache2-foreground".into(),
                detected_files: vec!["wp-config.php".into()],
                is_multi_service: true,
                generated_yaml: format!(
r#"# Generated by myBox (https://ucdreams.com)


services:
  wordpress:
    image: wordpress:php8.3-apache
    ports:
      - "{port}:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_pass
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_pass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - mybox_wp_db:/var/lib/mysql

volumes:
  mybox_wp_db:
"#, port=port),
                services: vec![
                    DetectedService { name: "wordpress".into(), role: "WordPress + Apache".into(), image: "wordpress:php8.3-apache".into(), port, env_vars: vec!["WORDPRESS_DB_HOST".into()] },
                    DetectedService { name: "db".into(), role: "MySQL 8.0 Database".into(), image: "mysql:8.0".into(), port: 3306, env_vars: vec!["MYSQL_DATABASE".into()] },
                ],
            };
        }

        // 5. Rust (Cargo.toml)
        if root.join("Cargo.toml").exists() {
            let port = Self::find_available_port(8080);
            return DetectedProject {
                framework_id: "rust".into(),
                name: "Rust Web / System Application".into(),
                category: "Rust".into(),
                description: "Detected Rust project (Cargo workspace or binary crate)".into(),
                default_port: port,
                icon: "rust".into(),
                runtime_image: "rust:alpine".into(),
                start_command: "cargo run".into(),
                detected_files: vec!["Cargo.toml".into()],
                is_multi_service: false,
                generated_yaml: format!(
r#"# Generated by myBox (https://ucdreams.com)


services:
  app:
    image: rust:alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "{port}:8080"
    command: sh -c "cargo run"
"#, port=port),
                services: vec![DetectedService { name: "app".into(), role: "Rust Binary Server".into(), image: "rust:alpine".into(), port, env_vars: vec![] }],
            };
        }

        // 6. Go (go.mod)
        if root.join("go.mod").exists() || root.join("main.go").exists() {
            let port = Self::find_available_port(8080);
            return DetectedProject {
                framework_id: "go".into(),
                name: "Go (Golang) Microservice".into(),
                category: "Go".into(),
                description: "Detected Go project with go.mod module manifest".into(),
                default_port: port,
                icon: "go".into(),
                runtime_image: "golang:1.22-alpine".into(),
                start_command: "go run .".into(),
                detected_files: vec!["go.mod".into()],
                is_multi_service: false,
                generated_yaml: format!(
r#"# Generated by myBox (https://ucdreams.com)


services:
  api:
    image: golang:1.22-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "{port}:8080"
    command: sh -c "go run ."
"#, port=port),
                services: vec![DetectedService { name: "api".into(), role: "Go API Service".into(), image: "golang:1.22-alpine".into(), port, env_vars: vec![] }],
            };
        }

        // 7. Ruby (Gemfile)
        if root.join("Gemfile").exists() {
            let gem_content = std::fs::read_to_string(root.join("Gemfile")).unwrap_or_default().to_lowercase();
            let is_rails = gem_content.contains("rails") || root.join("config/application.rb").exists();
            let name = if is_rails { "Ruby on Rails App" } else { "Ruby Application" };
            let cmd = if is_rails { "bundle exec rails server -b 0.0.0.0 -p 3000" } else { "ruby app.py" };
            let base_port = if is_rails { 3000 } else { 4567 };
            let port = Self::find_available_port(base_port);

            return DetectedProject {
                framework_id: "ruby".into(),
                name: name.into(),
                category: "Ruby".into(),
                description: "Detected Ruby application with Bundler Gemfile".into(),
                default_port: port,
                icon: "ruby".into(),
                runtime_image: "ruby:3.3-alpine".into(),
                start_command: cmd.into(),
                detected_files: vec!["Gemfile".into()],
                is_multi_service: false,
                generated_yaml: format!(
r#"# Generated by myBox (https://ucdreams.com)


services:
  web:
    image: ruby:3.3-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "{port}:{base_port}"
    command: sh -c "bundle install 2>/dev/null || true && {cmd}"
"#, port=port, base_port=base_port, cmd=cmd),
                services: vec![DetectedService { name: "web".into(), role: "Ruby App".into(), image: "ruby:3.3-alpine".into(), port, env_vars: vec![] }],
            };
        }

        // 8. Java / JVM / Spring Boot (pom.xml, build.gradle)
        if root.join("pom.xml").exists() || root.join("build.gradle").exists() || root.join("build.gradle.kts").exists() {
            let port = Self::find_available_port(8080);
            return DetectedProject {
                framework_id: "springboot".into(),
                name: "Java / Spring Boot".into(),
                category: "Java / JVM".into(),
                description: "Detected Java Maven / Gradle Spring Boot backend application".into(),
                default_port: port,
                icon: "java".into(),
                runtime_image: "eclipse-temurin:21-alpine".into(),
                start_command: "./mvnw spring-boot:run || ./gradlew bootRun".into(),
                detected_files: vec!["pom.xml".into()],
                is_multi_service: false,
                generated_yaml: format!(
r#"# Generated by myBox (https://ucdreams.com)


services:
  app:
    image: eclipse-temurin:21-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "{port}:8080"
    command: sh -c "./mvnw spring-boot:run 2>/dev/null || ./gradlew bootRun 2>/dev/null || java -jar target/*.jar"
"#, port=port),
                services: vec![DetectedService { name: "app".into(), role: "Spring Boot Server".into(), image: "eclipse-temurin:21-alpine".into(), port, env_vars: vec![] }],
            };
        }

        // 9. .NET / C# / ASP.NET
        let has_csproj = std::fs::read_dir(root)
            .map(|entries| entries.filter_map(|e| e.ok()).any(|e| e.file_name().to_string_lossy().ends_with(".csproj") || e.file_name().to_string_lossy().ends_with(".sln")))
            .unwrap_or(false);

        if has_csproj || root.join("Program.cs").exists() {
            let port = Self::find_available_port(5000);
            return DetectedProject {
                framework_id: "dotnet".into(),
                name: ".NET / ASP.NET Core API".into(),
                category: ".NET".into(),
                description: "Detected .NET / C# application project".into(),
                default_port: port,
                icon: "dotnet".into(),
                runtime_image: "mcr.microsoft.com/dotnet/sdk:8.0-alpine".into(),
                start_command: "dotnet run --urls=http://0.0.0.0:5000".into(),
                detected_files: vec!["*.csproj".into()],
                is_multi_service: false,
                generated_yaml: format!(
r#"# Generated by myBox (https://ucdreams.com)


services:
  api:
    image: mcr.microsoft.com/dotnet/sdk:8.0-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "{port}:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
    command: sh -c "dotnet run --urls=http://0.0.0.0:5000"
"#, port=port),
                services: vec![DetectedService { name: "api".into(), role: ".NET Core App".into(), image: "mcr.microsoft.com/dotnet/sdk:8.0-alpine".into(), port, env_vars: vec!["ASPNETCORE_URLS=http://+:5000".into()] }],
            };
        }

        // 10. Flutter / Dart (pubspec.yaml)
        if root.join("pubspec.yaml").exists() {
            let port = Self::find_available_port(8080);
            return DetectedProject {
                framework_id: "flutter".into(),
                name: "Flutter Web / Dart App".into(),
                category: "Mobile & Web".into(),
                description: "Detected Flutter / Dart project (pubspec.yaml found)".into(),
                default_port: port,
                icon: "flutter".into(),
                runtime_image: "ghcr.io/cirruslabs/flutter:latest".into(),
                start_command: "flutter run -d web-server --web-port 8080 --web-hostname 0.0.0.0".into(),
                detected_files: vec!["pubspec.yaml".into()],
                is_multi_service: false,
                generated_yaml: format!(
r#"# Generated by myBox (https://ucdreams.com)


services:
  web:
    image: ghcr.io/cirruslabs/flutter:latest
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "{port}:8080"
    command: sh -c "flutter pub get && flutter run -d web-server --web-port 8080 --web-hostname 0.0.0.0"
"#, port=port),
                services: vec![DetectedService { name: "web".into(), role: "Flutter Web Server".into(), image: "ghcr.io/cirruslabs/flutter:latest".into(), port, env_vars: vec![] }],
            };
        }

        // Fallback default
        Self::fallback_default("General Fullstack + PostgreSQL", 3000)
    }

    fn generate_node_yaml(container_port: u16, command: &str) -> (u16, String) {
        let host_port = Self::find_available_port(container_port);
        let yaml = format!(
r#"# Auto-generated by myBox (https://ucdreams.com)
services:
  web:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "{host_port}:{container_port}"
    environment:
      - NODE_ENV=development
      - PORT={container_port}
    command: sh -c "npm install 2>/dev/null || true && {command}"
"#, host_port=host_port, container_port=container_port, command=command);
        (host_port, yaml)
    }

    fn fallback_default(name: &str, preferred_port: u16) -> DetectedProject {
        let port = Self::find_available_port(preferred_port);
        let yaml = format!(
r#"# Generated by myBox (https://ucdreams.com)


services:
  app:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "{port}:{preferred_port}"
    environment:
      - DATABASE_URL=postgres://mybox:mybox123@db:5432/mybox_db
    command: sh -c "npm install 2>/dev/null || true && npm start"
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: mybox
      POSTGRES_PASSWORD: mybox123
      POSTGRES_DB: mybox_db
    ports:
      - "5432:5432"
    volumes:
      - mybox_pgdata:/var/lib/postgresql/data

volumes:
  mybox_pgdata:
"#, port=port, preferred_port=preferred_port);

        DetectedProject {
            framework_id: "generic_fullstack".into(),
            name: name.into(),
            category: "General Application".into(),
            description: "Ready-to-run container sandbox with persistent PostgreSQL database".into(),
            default_port: port,
            icon: "database".into(),
            runtime_image: "node:20-alpine & postgres:16-alpine".into(),
            start_command: "mybox up".into(),
            detected_files: vec![],
            is_multi_service: true,
            generated_yaml: yaml,
            services: vec![
                DetectedService { name: "app".into(), role: "Application Server".into(), image: "node:20-alpine".into(), port, env_vars: vec!["DATABASE_URL".into()] },
                DetectedService { name: "db".into(), role: "PostgreSQL Database".into(), image: "postgres:16-alpine".into(), port: 5432, env_vars: vec!["POSTGRES_DB".into()] },
            ],
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    fn create_temp_dir(name: &str) -> std::path::PathBuf {
        let dir = std::env::temp_dir().join(format!("mybox_test_{}_{}", name, std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_nanos()));
        fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn test_find_available_port() {
        let port = FrameworkDetector::find_available_port(3000);
        assert!(port >= 3000);
        // Verify port can be bound
        assert!(std::net::TcpListener::bind(("127.0.0.1", port)).is_ok());
    }

    #[test]
    fn test_detect_nextjs() {
        let dir = create_temp_dir("nextjs");
        fs::write(dir.join("package.json"), r#"{"dependencies": {"next": "^14.0.0", "react": "^18"}}"#).unwrap();
        fs::write(dir.join("next.config.js"), "module.exports = {};").unwrap();

        let res = FrameworkDetector::detect(dir.to_str().unwrap());
        assert_eq!(res.framework_id, "nextjs");
        assert!(res.default_port >= 3000);
        assert_eq!(res.runtime_image, "node:20-alpine");
        assert!(res.generated_yaml.contains("node:20-alpine"));
        let _ = fs::remove_dir_all(dir);
    }

    #[test]
    fn test_detect_react_vite() {
        let dir = create_temp_dir("vite");
        fs::write(dir.join("package.json"), r#"{"dependencies": {"react": "^18"}, "devDependencies": {"vite": "^5"}}"#).unwrap();
        fs::write(dir.join("vite.config.ts"), "export default {};").unwrap();

        let res = FrameworkDetector::detect(dir.to_str().unwrap());
        assert_eq!(res.framework_id, "vite");
        assert!(res.default_port >= 5173);
        let _ = fs::remove_dir_all(dir);
    }

    #[test]
    fn test_detect_django() {
        let dir = create_temp_dir("django");
        fs::write(dir.join("manage.py"), "#!/usr/bin/env python\nimport os\n").unwrap();

        let res = FrameworkDetector::detect(dir.to_str().unwrap());
        assert_eq!(res.framework_id, "django");
        assert!(res.default_port >= 8000);
        assert_eq!(res.runtime_image, "python:3.12-slim");
        assert!(res.generated_yaml.contains("manage.py runserver"));
        let _ = fs::remove_dir_all(dir);
    }

    #[test]
    fn test_detect_fastapi() {
        let dir = create_temp_dir("fastapi");
        fs::write(dir.join("requirements.txt"), "fastapi==0.110.0\nuvicorn==0.28.0\n").unwrap();
        fs::write(dir.join("main.py"), "from fastapi import FastAPI\napp = FastAPI()\n").unwrap();

        let res = FrameworkDetector::detect(dir.to_str().unwrap());
        assert_eq!(res.framework_id, "python");
        assert!(res.default_port >= 8000);
        assert!(res.generated_yaml.contains("uvicorn main:app"));
        let _ = fs::remove_dir_all(dir);
    }

    #[test]
    fn test_detect_laravel() {
        let dir = create_temp_dir("laravel");
        fs::write(dir.join("artisan"), "#!/usr/bin/env php\n").unwrap();
        fs::write(dir.join("composer.json"), r#"{"require": {"laravel/framework": "^11.0"}}"#).unwrap();

        let res = FrameworkDetector::detect(dir.to_str().unwrap());
        assert_eq!(res.framework_id, "laravel");
        assert!(res.default_port >= 8000);
        assert_eq!(res.runtime_image, "php:8.3-cli-alpine");
        let _ = fs::remove_dir_all(dir);
    }

    #[test]
    fn test_detect_wordpress() {
        let dir = create_temp_dir("wordpress");
        fs::write(dir.join("wp-config.php"), "<?php define('DB_NAME', 'wp');").unwrap();

        let res = FrameworkDetector::detect(dir.to_str().unwrap());
        assert_eq!(res.framework_id, "wordpress");
        assert!(res.default_port >= 8080);
        assert!(res.is_multi_service);
        assert_eq!(res.services.len(), 2); // wordpress + db
        let _ = fs::remove_dir_all(dir);
    }

    #[test]
    fn test_detect_ruby_rails() {
        let dir = create_temp_dir("rails");
        fs::write(dir.join("Gemfile"), "source 'https://rubygems.org'\ngem 'rails', '~> 7.1'\n").unwrap();

        let res = FrameworkDetector::detect(dir.to_str().unwrap());
        assert_eq!(res.framework_id, "ruby");
        assert!(res.default_port >= 3000);
        assert_eq!(res.runtime_image, "ruby:3.3-alpine");
        let _ = fs::remove_dir_all(dir);
    }

    #[test]
    fn test_detect_rust() {
        let dir = create_temp_dir("rust");
        fs::write(dir.join("Cargo.toml"), "[package]\nname = \"test_app\"\nversion = \"0.1.0\"\n").unwrap();

        let res = FrameworkDetector::detect(dir.to_str().unwrap());
        assert_eq!(res.framework_id, "rust");
        assert!(res.default_port >= 8080);
        assert_eq!(res.runtime_image, "rust:alpine");
        let _ = fs::remove_dir_all(dir);
    }

    #[test]
    fn test_detect_go() {
        let dir = create_temp_dir("golang");
        fs::write(dir.join("go.mod"), "module example.com/myapp\n\ngo 1.22\n").unwrap();

        let res = FrameworkDetector::detect(dir.to_str().unwrap());
        assert_eq!(res.framework_id, "go");
        assert!(res.default_port >= 8080);
        assert_eq!(res.runtime_image, "golang:1.22-alpine");
        let _ = fs::remove_dir_all(dir);
    }

    #[test]
    fn test_detect_spring_boot() {
        let dir = create_temp_dir("springboot");
        fs::write(dir.join("pom.xml"), "<project><parent><artifactId>spring-boot-starter-parent</artifactId></parent></project>").unwrap();

        let res = FrameworkDetector::detect(dir.to_str().unwrap());
        assert_eq!(res.framework_id, "springboot");
        assert!(res.default_port >= 8080);
        assert_eq!(res.runtime_image, "eclipse-temurin:21-alpine");
        let _ = fs::remove_dir_all(dir);
    }

    #[test]
    fn test_detect_dotnet() {
        let dir = create_temp_dir("dotnet");
        fs::write(dir.join("MyApp.csproj"), "<Project Sdk=\"Microsoft.NET.Sdk.Web\"></Project>").unwrap();

        let res = FrameworkDetector::detect(dir.to_str().unwrap());
        assert_eq!(res.framework_id, "dotnet");
        assert!(res.default_port >= 5000);
        assert_eq!(res.runtime_image, "mcr.microsoft.com/dotnet/sdk:8.0-alpine");
        let _ = fs::remove_dir_all(dir);
    }

    #[test]
    fn test_detect_flutter() {
        let dir = create_temp_dir("flutter");
        fs::write(dir.join("pubspec.yaml"), "name: flutter_app\nflutter:\n  uses-material-design: true\n").unwrap();

        let res = FrameworkDetector::detect(dir.to_str().unwrap());
        assert_eq!(res.framework_id, "flutter");
        assert!(res.default_port >= 8080);
        let _ = fs::remove_dir_all(dir);
    }

    #[test]
    fn test_detect_multi_service() {
        let dir = create_temp_dir("multiservice");
        fs::create_dir_all(dir.join("frontend")).unwrap();
        fs::create_dir_all(dir.join("backend")).unwrap();

        let res = FrameworkDetector::detect(dir.to_str().unwrap());
        assert_eq!(res.framework_id, "fullstack_multi");
        assert!(res.is_multi_service);
        assert_eq!(res.services.len(), 4); // frontend, backend, database, cache
        assert!(res.generated_yaml.contains("postgres:16-alpine"));
        assert!(res.generated_yaml.contains("redis:7.2-alpine"));
        let _ = fs::remove_dir_all(dir);
    }
}

