use anyhow::{Context, Result};
use std::path::Path;
use tokio::process::Command;

#[derive(Clone)]
pub struct ProjectManager;

impl ProjectManager {
    pub async fn launch_project(
        project_path: &str,
        project_type: &str,
        port: u16,
    ) -> Result<String> {
        let path = Path::new(project_path);
        if !path.exists() {
            anyhow::bail!("Project directory does not exist: {}", project_path);
        }

        let mybox_yaml = path.join("mybox.yaml");
        let mybox_yml = path.join("mybox.yml");
        let docker_compose = path.join("docker-compose.yml");
        let boxfile = path.join("Boxfile");
        let dockerfile = path.join("Dockerfile");

        // If no configuration exists, auto-generate standard myBox config
        if !mybox_yaml.exists() && !mybox_yml.exists() && !docker_compose.exists() && !boxfile.exists() && !dockerfile.exists() {
            Self::generate_project_config(path, project_type, port)?;
        }

        // Run project using compose / mybox runner
        Self::compose_up(Some(project_path.to_string())).await
    }

    fn generate_project_config(path: &Path, project_type: &str, port: u16) -> Result<()> {
        match project_type.to_lowercase().as_str() {
            "node" | "react" | "next" | "frontend" => {
                let content = format!(
                    r#"# Generated by myBox (https://ucdreams.com)


services:
  web:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "{port}:{port}"
    command: sh -c "npm install && npm start"
"#,
                    port = port
                );
                std::fs::write(path.join("mybox.yaml"), content)?;
            }
            "python" | "django" | "fastapi" | "flask" => {
                let content = format!(
                    r#"# Generated by myBox (https://ucdreams.com)


services:
  api:
    image: python:3.12-slim
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "{port}:{port}"
    command: sh -c "pip install -r requirements.txt 2>/dev/null || true && python main.py"
"#,
                    port = port
                );
                std::fs::write(path.join("mybox.yaml"), content)?;
            }
            "php" | "wordpress" | "laravel" => {
                let content = format!(
                    r#"# Generated by myBox (https://ucdreams.com)


services:
  web:
    image: php:8.3-apache
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "{port}:80"
"#,
                    port = port
                );
                std::fs::write(path.join("mybox.yaml"), content)?;
            }
            "fullstack" | "database" | _ => {
                let content = format!(
                    r#"# Generated by myBox (https://ucdreams.com)


services:
  app:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "{port}:{port}"
    environment:
      - DATABASE_URL=postgres://mybox:mybox123@db:5432/mybox_db
    command: sh -c "npm install && npm start"
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: mybox
      POSTGRES_PASSWORD: mybox123
      POSTGRES_DB: mybox_db
    ports:
      - "5432:5432"
    volumes:
      - mybox_pgdata:/var/lib/postgresql/data

volumes:
  mybox_pgdata:
"#,
                    port = port
                );
                std::fs::write(path.join("mybox.yaml"), content)?;
            }
        }

        Ok(())
    }

    pub async fn compose_up(path: Option<String>) -> Result<String> {
        let work_dir = path.unwrap_or_else(|| ".".to_string());
        let target_path = Path::new(&work_dir);

        // Check if mybox.yaml or mybox.yml exists
        let compose_file = if target_path.join("mybox.yaml").exists() {
            "mybox.yaml"
        } else if target_path.join("mybox.yml").exists() {
            "mybox.yml"
        } else if target_path.join("docker-compose.yml").exists() {
            "docker-compose.yml"
        } else if target_path.join("docker-compose.yaml").exists() {
            "docker-compose.yaml"
        } else {
            "mybox.yaml"
        };

        let output = Command::new("docker")
            .args(["compose", "-f", compose_file, "up", "-d"])
            .current_dir(&work_dir)
            .output()
            .await;

        let is_docker_offline = match output {
            Ok(ref out) => {
                if !out.status.success() {
                    let stderr = String::from_utf8_lossy(&out.stderr);
                    stderr.contains("Cannot connect") || stderr.contains("docker daemon") || stderr.contains("connection refused")
                } else {
                    false
                }
            }
            Err(_) => true,
        };

        if is_docker_offline {
            // 100% Docker-Free Native Execution Fallback
            let detected = crate::detector::FrameworkDetector::detect(&work_dir);
            return crate::native_runner::NativeRunner::launch_project_natively(&work_dir, &detected).await;
        }

        let output = output.context("Failed to execute compose engine.")?;

        if !output.status.success() {
            // If any image pull or daemon failure, fall back to native execution
            let detected = crate::detector::FrameworkDetector::detect(&work_dir);
            return crate::native_runner::NativeRunner::launch_project_natively(&work_dir, &detected).await;
        }

        Ok(format!(
            "✓ Project launched successfully using {}",
            compose_file
        ))
    }

    pub async fn compose_down(path: Option<String>) -> Result<String> {
        let work_dir = path.unwrap_or_else(|| ".".to_string());
        let target_path = Path::new(&work_dir);

        // 1. Stop native services if running
        let _ = crate::native_runner::NativeRunner::global().stop_all_for_project(&work_dir).await;

        let compose_file = if target_path.join("mybox.yaml").exists() {
            "mybox.yaml"
        } else if target_path.join("mybox.yml").exists() {
            "mybox.yml"
        } else {
            "docker-compose.yml"
        };

        let _ = Command::new("docker")
            .args(["compose", "-f", compose_file, "down"])
            .current_dir(&work_dir)
            .output()
            .await;

        Ok("✓ Project sandboxes stopped and cleaned up.".into())
    }

    pub async fn remove_project(path: Option<String>, delete_config: bool) -> Result<String> {
        let work_dir = path.unwrap_or_else(|| ".".to_string());
        let target_path = Path::new(&work_dir);

        // 1. Stop and tear down all running containers
        let _ = Self::compose_down(Some(work_dir.clone())).await;

        // 2. If delete_config is true, delete mybox.yaml / mybox.yml
        if delete_config {
            let mut deleted = Vec::new();
            for filename in &["mybox.yaml", "mybox.yml", "mybox.json"] {
                let file_path = target_path.join(filename);
                if file_path.exists() {
                    let _ = std::fs::remove_file(&file_path);
                    deleted.push(*filename);
                }
            }

            if !deleted.is_empty() {
                return Ok(format!("✓ De-containerized successfully and removed {}", deleted.join(", ")));
            }
        }

        Ok("✓ Project containers removed successfully.".into())
    }
}

